### ISSUE TITLE
Issue with building model

### ISSUE THREAD

**Issue by ccapo** [brianvanleeuwen/Halite-ML-starter-bot#2]
I tried running train_bot.py on the replay files, but the number of epochs in the fitting portion never exceeds 4 or 5 out of 100. Is that supposed to happen?

Then when I try loading the model after it completes, the bot remains stationary throughout the run.

Am I am missing something?

**Comment by brianvanleeuwen** [comment]
The 4 or 5 epochs is expected, that is just early stopping kicking in.  For the stationary problem, make sure your copy of the training code is up to date with the repo's.

**Comment by brianvanleeuwen** [comment]
Specifically, make sure you have min(100,len(moves)) on L44.  Prior to that update my tests were stationary too.

**Comment by ccapo** [comment]
I made sure I have the latest version of your files, but the bot still remains stationary.

Does it matter how many files you train on? Because I have tried between 1 - 10 files so that I can get immediate feedback.

I'm also using python v3.5.2 to run train_bot.py, but I also have python v2.7 on my system. Though I did install the components using pip for python v3. Hopefully there aren't any conflicts.

**Comment by brianvanleeuwen** [comment]
The problem is likely the small number of samples you are using.  The bot tends to learn that most moves are still before it learns anything else.

**Comment by ccapo** [comment]
I have the same issue when I use the entire set of replay files, so I'm wondering if I have change any of the parameters in train_bot.py (e.g. increase the minimum number of moves to consider, or remove the stopping early callback along with increasing the number of epochs for training)? Or am I supposed to run train_bot.py multiple times?

**Comment by brianvanleeuwen** [comment]
You should only need to run train_bot.py once.  It will just overwrite model.h5 if you run it multiple times anyway.

I've added stratified sampling.  Please test whether this fixes your issue.

Edit: never mind, it didn't work.
