### ISSUE TITLE
sure about the minus ?

### ISSUE THREAD

**Issue by mariogeiger** [brianvanleeuwen/Halite-ML-starter-bot#3]
Are you sure about the minus `position` at these lines 

https://github.com/brianvanleeuwen/Halite-ML-starter-bot/blob/master/train_bot.py#L25-L26

?

**Comment by brianvanleeuwen** [comment]
Yes, it moves the array to be centered correctly.

**Comment by brianvanleeuwen** [comment]
Thanks for catching this @antigol , this was in fact a mistake.
