### ISSUE TITLE
Error when running offline with Halite Game Environment

### ISSUE THREAD

**Issue by CP121** [brianvanleeuwen/Halite-ML-starter-bot#8]
I have trained a model using your code. When **submitted**, it performs fine. However, when I try to run it offline using the Halite Game Environment I get this error:
```

 --- Init ---
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
 --- Bot used 233 milliseconds ---
-----------------------------------------------------------------------------
 --- Frame #1 ---
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
 --- Bot used 0 milliseconds ---
ERRORED!
Response received (if any):
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
 --- Bot was killed. Below is the rest of its output (if any): ---
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally

 --- End bot output ---

```

Do you know what the error could be? All the files were unchanged. 

I have tested the Python starter bots with the Halite Game Environment, and they work fine. Thanks.

**Comment by brianvanleeuwen** [comment]
Unfortunately I don't have a good solution for this. Someone posted about this on the Halite forum: http://forums.halite.io/t/ml-starter-bot-tutorial/616/19?u=brianvanleeuwen . Their solution was to create a separate environment that used the CPU only version of tensorflow.

**Comment by CP121** [comment]
Thanks for your message. I have got this working by switching the Keras backend from Tensorflow to Theano. The problem is caused by Tensorflow producing very ''noisy" logging output to stdout.
